# Demo

In [1]:
import warnings
warnings.filterwarnings('ignore')

from sklearn import preprocessing
import numpy as np

In [2]:
scaler = preprocessing.MinMaxScaler()
weights= np.array([115, 140, 175]).reshape(3, 1)
scaler.fit_transform(weights)

array([[ 0.        ],
       [ 0.41666667],
       [ 1.        ]])

# 练习

In [3]:
import pickle
import numpy
import matplotlib.pyplot as plt
import pandas as pd
import sys
sys.path.append("../tools/")
from feature_format import featureFormat, targetFeatureSplit

### load in the dict of dicts containing all the data on each person in the dataset
data_dict = pickle.load( open("../final_project/final_project_dataset.pkl", "r") )
### there's an outlier--remove it! 
data_dict.pop("TOTAL", 0)

df = pd.DataFrame(data_dict).transpose()

In [4]:
scaler = preprocessing.MinMaxScaler()
arr = df['salary'].values
arr = arr[arr != "NaN"].reshape(-1, 1)
scaler.fit(arr)
scaler.transform([[200000]])

array([[ 0.17962407]])

In [5]:
scaler = preprocessing.MinMaxScaler()
arr = df['exercised_stock_options'].values
arr = arr[arr != "NaN"].reshape(-1, 1)
scaler.fit(arr)
scaler.transform([[1000000]])


array([[ 0.02902059]])